language: scala

scala:
    - 2.11.0

jdk:
    - oraclejdk8

env:
   - PLAY_VERSION=2.5.0

before_script:
   - wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
   - unzip -q play-${PLAY_VERSION}.zip

script: 
   - play-${PLAY_VERSION}/play deps --sync
