Template.paperaccess.onRendered(function() {

	$(document).ready(function() {

		var config = {
			siteURL: 'accesspaper', // Change this to your site
			searchSite: true,
			type: 'web',
			append: false,
			perPage: 8, // A maximum of 8 is allowed by Google
			page: 0 // The start page
		}


		// Adding the site domain as a label for the first radio button:



		$('#searchForm').submit(function() {
			var input = $("#accesspaper").val();
			getPaperByKeyWord(input);
		});

	    function getPaperByKeyWord(input,settings){
	    	var stringUrl = "http://localhost:9000/accesspaper/"+input;
				var paperaccessresultsDiv = $('#paperaccrssresultsDiv');
	            $.ajax({
	                type : "GET",
	                contentType : "application/x-www-form-urlencoded; charset=utf-8",
	                url : stringUrl,
	                //User-Agent: 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081130 Minefield/3.1b3pre'
	                dataType: 'json',
	                cache : false,
	                success : function(response) {
	                console.log("yuanyuan");
	               // console.log("Data Loaded: " + JSON.stringify(response));
	                $('#more').remove();
	                var results=response;
	                console.log(results);
	                if (results.length) {

					// If results were returned, add them to a pageContainer div,
					// after which append them to the #resultsDiv:

					var pageContainer = $('<div>', {
						className: 'pageContainer'
					});
					for (var i = 0; i < results.length; i++) {
						// Creating a new result object and firing its toString method:
						console.log(results[i]);
						pageContainer.append(new result(results[i]) + '');
					}
	        paperaccessresultsDiv.empty();
					pageContainer.append('<div class="clear"></div>')
						.hide().appendTo(paperaccessresultsDiv)
						.fadeIn('slow');

				    } else{

					paperaccessresultsDiv.empty();
					$('<p>', {
						className: 'notFound',
						html: 'No Results Were Found!'
					}).hide().appendTo(paperaccessresultsDiv).fadeIn();

				    }
	               },
	                error : function(xhr, textStatus, errorThrown) {
	                	console.log("sdssdsd");
	                    console.log("error : " + textStatus);
	                }
	            });
	    }
			// This is class definition. Object of this class are created for
			// each result. The markup is generated by the .toString() method.
      function result(r) {

        // This is class definition. Object of this class are created for
        // each result. The markup is generated by the .toString() method.
            console.log(r.GsearchResultClass);
            var author = r.authors;
        var arr = [];
            arr = [
              '<div class="webResult">',
            '<form id="searchForm1" method="GET">',
            '<h2><a href="./paperaccess/paperedit",  onclick="location.href=this.href+'?key='+author;return false;" =>'r.title'</a></h2>',
           ' </form>',
            '</div>'
          ];

        // The toString method.
        this.toString = function() {
          return arr.join('');
        }
      }
	});
}
